### ISSUE TITLE
import가 잘못된거 같아요

### ISSUE THREAD

**Issue by nove1080** [belljun3395/practiceCRUD#4]
https://github.com/belljun3395/practiceCRUD/blob/2636621ee87ae78b4129040a4b41fab4e36dae03/src/main/java/com/example/demo/security/context/TokenAuditHolder.java#L3C1-L3C1

혹시 "import com.example.demo.security.authentication.token.TokenUserDetails" 이걸로 변경하는게 맞을까요?

**Comment by belljun3395** [comment]
네! 
다른 곳에서 가지고 오다보니 잘못들어깄네요..!
확인이 부족했습니다ㅠㅠ
